server:
  port: 8200



eureka:
  instance:
    hostname: projectapi1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
spring:
  application:
    name: projectApi1
